apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    name: app2
spec:
  initContainers:
    - name: init1
      image: ubuntu:latest
      command: [ '/usr/bin/sleep', ' 10s' ]
  containers:
  - name: db
    image: mahendrshinde/mysql-sample:employees
    resources:
      limits:
        memory: "256Mi"
        cpu: "200m"
    ports:
      - containerPort: 3306
