apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  replicas: 3
  revisionHistoryLimit: 4
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 2
  #    maxUnavailable: 2
  strategy: 
    type: Recreate
    
  minReadySeconds: 10
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: myapp
        image: mahendrshinde/myweb:1
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 80