apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: mahendra
spec:
  selector:
    matchLabels:
      app: app8
  serviceName: web-service
  replicas: 3
  template:
    metadata:
      labels:
        app: app8
    spec:
      containers:
      - name: myapp
        image: nginx:alpine
        resources:
          limits:
            cpu: '200m'
            memory: '64Mi'
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      storageClassName: azurefile
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: mahendra
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: app8
  ports:
  - port: 80
    targetPort: web
