apiVersion: v1
kind: Pod
metadata:
  name: app5
  labels:
    name: app5
spec:
  volumes:
  - name: vol1
    secret: 
      secretName: mysecrets

  containers:
  - name: myapp
    image: nginx:alpine
    volumeMounts:
      - mountPath: /vars
        name: vol1
    resources:
      limits:
        memory: "32Mi"
        cpu: "50m"
    ports:
      - containerPort: 80