apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    name: app3
spec:
  containers:
  - name: myapp
    image: nginx:alpine
    envFrom:
    - configMapRef:
        name: dbconfig
        #optional: true
    resources:
      limits:
        memory: "16Mi"
        cpu: "50m"
    ports:
      - containerPort: 80
